forum/forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum_web.urls'))
]

forum/forum_web/urls.py
from django.urls import path
from . import views
app_name = 'forum'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # Auth urls
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Registration.as_view(), name='registration'),
    # Post urls
    path('posts/', views.PostList.as_view(), name='post_list'),
    path('posts/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('posts/create', views.PostCreate.as_view(), name='post_create'),
    path('posts/update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('posts/delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    # Comment urls
    path('comments/create', views.CommentCreate.as_view(), name='comment_create'),
    path('comment/delete/<int:pk>', views.CommentDelete.as_view(), name='comment_delete'),
    # User urls
    path('user/<int:pk>', views.UserDetail.as_view(), name='user_detail')
]

forum/forum_web/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

forum/forum_web/forms.py
from django.forms import ModelForm, fields
from .models import Post, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'text']


class CommentForm(ModelForm):
    post = fields.HiddenInput()

    class Meta:
        model = Comment
        fields = ['text']

forum/forum_web/views.py
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView
from .models import Post, Comment
from django.urls import reverse_lazy
from django.contrib.auth import logout, models
from .forms import CommentForm, PostForm, LoginForm, RegistrationForm
from django.http import HttpResponseRedirect


class IndexView(generic.RedirectView):
    url = reverse_lazy('forum:post_list')


# Auth views
class Login(LoginView):
    redirect_field_name = ''
    redirect_authenticated_user = True
    authentication_form = LoginForm
    template_name = 'registration/login.html'


class Logout(LogoutView):
    url = reverse_lazy('forum:post_list')

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url()


class UserDetail(generic.DetailView):
    model = models.User
    template_name = 'forum_web/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(user=self.request.user.id)
        return context


class Registration(generic.CreateView):
    form_class = RegistrationForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('forum:post_list')


# Post views
class PostList(generic.ListView):
    model = Post
    template_name = 'forum_web/post_list.html'
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 20


class PostDetail(generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        context['comments'] = Comment.objects.filter(post=context['post'].id).order_by('-created_at')
        return context


class PostCreate(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'forum_web/post_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_type'] = 'Create'
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = models.User.objects.get(id=self.request.user.id)
        post.save()
        return HttpResponseRedirect(reverse_lazy('forum:user_detail', kwargs={'pk': self.request.user.id}))

    def get_success_url(self):
        return reverse_lazy('forum:user_detail', kwargs={'pk': self.request.user.id})


class PostUpdate(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'forum_web/post_edit.html'

    def get_success_url(self):
        return reverse_lazy('forum:user_detail', kwargs={'pk': self.request.user.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_type'] = 'Update'
        return context


class PostDelete(generic.DeleteView):
    model = Post
    template_name = 'forum_web/post_delete.html'

    def get_success_url(self):
        return reverse_lazy('forum:user_detail', kwargs={'pk': self.request.user.id})


# Comment views
class CommentCreate(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = Post.objects.get(id=self.request.POST['post'])
        comment.user = models.User.objects.get(id=self.request.user.id)
        comment.save()
        return HttpResponseRedirect(reverse_lazy('forum:post_detail', kwargs={'pk': self.request.POST['post']}))


class CommentDelete(generic.DeleteView):
    model = Comment
    template_name = 'forum_web/comment_delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = reverse_lazy('forum:post_detail', kwargs={'pk': self.object.post.id})
        self.object.delete()
        return HttpResponseRedirect(success_url)

forum/forum_web/templates/forum_web/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forum app</title>
</head>
<body>
<h1>Forum app</h1>
{% if user.is_authenticated %}
<p>
    You are signed in as: <a href="{% url 'forum:user_detail' user.id %}">{{user.username}}</a>
</p>
<a href="{% url 'forum:logout' %}">Logout</a>
{% else %}
<a href="{% url 'forum:login' %}">Login</a>
<a href="{% url 'forum:registration' %}">Register</a>
{% endif %}
{% block content %}
{% endblock %}
{% block pagination %}
{% endblock %}
</body>
</html>

forum/forum_web/templates/forum_web/comment_delete.html
{% extends 'forum_web/base_template.html' %}

{% block content %}
<p>Are you sure you want to delete your comment?</p>
<form method="post" action="{% url 'forum:comment_delete' object.id %}">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% endblock %}

forum/forum_web/templates/forum_web/pagination_template.html
<p>Pages:</p>
{% for i in paginator.page_range %}
    {% if objects.number == i %}
        {{ i }}
    {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endif %}
{% endfor %}

forum/forum_web/templates/forum_web/post_delete.html
{% extends 'forum_web/base_template.html' %}

{% block content %}
<p>Are you sure you want to delete post {{ post.title }}</p>
<form method="post" action="{% url 'forum:post_delete' object.id %}">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% endblock %}

forum/forum_web/templates/forum_web/post_detail.html
{% extends 'forum_web/base_template.html' %}
{% block content %}
<div id="post-data">
    <h1>{{post.title}}</h1>
    <p>Category: {{post.category}}</p>
    <p>Created at: {{post.created_at}}</p>
    <p>Posted by: {{post.user}}</p>
    <p>{{post.text}}</p>
</div>
<div id="comment-list">
    {% for comment in comments %}
        <div id="comment-item">
            {{ comment.user }}
            {{ comment.created_at }}
            {{ comment.text }}
        </div>
    {% if comment.user.id == user.id %}
    <a href="{% url 'forum:comment_delete' comment.id %}">Delete comment</a>
    {% endif %}
    {% endfor %}
</div>
{% if user.is_authenticated %}
<form method="post" action="{% url 'forum:comment_create' %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="hidden" name="post" value="{{post.id}}">
    <input type="submit" value="Comment">
</form>
{% endif %}
{% endblock %}

forum/forum_web/templates/forum_web/post_edit.html
{% extends 'forum_web/base_template.html' %}

{% block content %}

<h1>{{ view_type }} post</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ view_type }}">
</form>
{% endblock %}

forum/forum_web/templates/forum_web/post_list.html
{% extends 'forum_web/base_template.html' %}
{% block content %}

{% for post in posts %}
<div id="post-list-item">
    <h2><a href="{% url 'forum:post_detail' post.id%}">{{post.title}}</a></h2>
    <h3>{{post.user}}</h3>
    <h3>{{post.category}}</h3>
    <h3>{{post.created_at}}</h3>
</div>
{% endfor %}
{% endblock %}

{% block pagination %}
    {% include 'forum_web/pagination_template.html' with objects=posts %}
{% endblock %}

forum/forum_web/templates/forum_web/user_detail.html
{% extends 'forum_web/base_template.html' %}

{% block content %}
<h3>{{ user.username }}</h3>
<a href="{% url 'forum:post_create' %}">Create post</a>
<h4>Your posts:</h4>
<ul>
    {% for post in posts %}
    <li>
        <a href="{% url 'forum:post_detail' post.id %}">{{ post.title }}</a>
        <a href="{% url 'forum:post_update' post.id %}">Update post</a>
        <a href="{% url 'forum:post_delete' post.id %}">Delete post</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}